<?php
/**
 * Module Designed to Fix the secure vs. insecure areas of the site resulting from our multi-system architecture (Drupal & Wordpress).
 */

function subtheme01_process_html(&$vars)
{
    foreach (array('head', 'styles', 'scripts') as $replace) {
        if (!isset($vars[$replace])) {
            continue;
        }

        $vars[$replace] = preg_replace('/(src|href|@import )(url\(|=)(")http(s?):/', '$1$2$3', $vars[$replace]);
    }
}